apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8stest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8stest
  template:
    metadata:
      labels:
        app: k8stest
    spec:
      containers:
        - name: k8stestapp
          image: k8stest/gosample:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
